### ISSUE TITLE
Get ride of "WARNING Deprecated: markdown_github. Use gfm"

### ISSUE THREAD

**Issue by dcousin3** [r-lib/pkgdown#1618]
This warning occurs when using pkgdow::build_site() for building articles as well as function references.

It is just a matter of changing the format with ``pandoc --from gfm`` but where can I change this default behavior? That does not seem to be an option in pkgdown.

I am using PANDOC 2.11.4; pkgdown 1.6.1 and R 4.0.3

**Comment by maelle** [comment]
I think this was fixed in the development version by #1473.

**Comment by marcosmolla** [comment]
> This warning occurs when using pkgdow::build_site() for building articles as well as function references.
> 
> It is just a matter of changing the format with `pandoc --from gfm` but where can I change this default behavior? That does not seem to be an option in pkgdown.
> 
> I am using PANDOC 2.11.4; pkgdown 1.6.1 and R 4.0.3

Hi, sorry to open this up again, but I don't understand the answer. 
Where can I change the format to gfm? What do I need to change to make this Warning message go away?
Many thanks!!

**Comment by dcousin3** [comment]
Hello Marco, When I upgraded the package, the message went away.

**Comment by marcosmolla** [comment]
Thanks for the fast reply. I updated all my packages and am currently on:
R version 4.0.5,
pandoc 2.13, and
pkgdown 1.6.1
But the Warning message persists. I mean, it's not a problem, I happily ignore a Warning message. Just wanted to let you know that I can still see it.

**Comment by maelle** [comment]
@marcosmolla this is only fixed in pkgdown development version for now, that you could install with `remotes::install_github("r-lib/pkgdown")`. (or you could wait until next release of course!) Sorry for being unclear in my first answer.

**Comment by marcosmolla** [comment]
Thanks @maelle, that worked indeed. Though, the development version affected the current theme I am using. I better wait for the next release. Thanks!

**Comment by maelle** [comment]
What happened to the theme, if you don't mind sharing? Just to make sure it's not a breaking change we are not aware of.

**Comment by marcosmolla** [comment]
All good. I noticed that the developer version is now supporting bootstrap version 4 themes?! Is that right? Apparently I had a line in the yaml file that turned the background dark, which was not recognised by the CRAN version before. I just set a new theme and it all looks great. 

Though, one thing I noticed: links in the README file (in my case e.g. https://doi.org/10.1126/sciadv.aaw0609) are not converted to clickable links but remain plain text. With the CRAN version they appear as hyper refs in a different colour.

**Comment by marcosmolla** [comment]
Okay, that's weird. I also noticed that the developer version (on the right in the picture) got rid of the entire first paragraph with a title and a logo (see local build on the left).  

<img width="1436" alt="Screenshot 2021-05-03 at 13 43 29" src="https://user-images.githubusercontent.com/8994342/116912170-de5f2480-ac15-11eb-89b8-e897abc8333b.png">

**Comment by maelle** [comment]
@marcosmolla thanks a lot for the reports! :bear: 

* Regarding the disappearing paragraph I've made a PR https://github.com/marcosmolla/complexNet/pull/1 -- the internal `badges_extract()` function was extracting the first section because it was glued to the badges.

* Regarding autolinking bare URIs (this is Pandoc linguo) I've opened a PR #1663

**Comment by maelle** [comment]
And yes Bootstrap 4 is now supported, the docs of site customization can be found at https://pkgdown.r-lib.org/dev/articles/customization.html (and the changelog at https://pkgdown.r-lib.org/dev/news/index.html#pkgdown-development-version-1).

**Comment by marcosmolla** [comment]
Awesome, thank you @maelle 
Also, that was my first Merge of a PR on GitHub. Very interesting.

**Comment by marcosmolla** [comment]
I should probably post that in a different place (is that its own issue) but the dev version of `pkgdown` does not automatically turn urls into hyper refs. See image (left CRAN version, right dev version). 

![Screenshot 2021-05-05 at 08 54 45](https://user-images.githubusercontent.com/8994342/117144281-bf7ca180-ad7f-11eb-8e5d-27f9bab2a105.png)

**Comment by maelle** [comment]
See #1663 that I had opened thanks to your report 😉

**Comment by marcosmolla** [comment]
Fantastic. I missed this.
