### ISSUE TITLE
details html tag

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#884]
I'm not sure this is a bug, and if it is one of what it is a bug, but here is how https://pkgdown.r-lib.org/articles/test/details.html looks for me on Firefox

![image](https://user-images.githubusercontent.com/8360597/48353275-507ed000-e68f-11e8-870a-50b7707e09b2.png)

Both "things" are clickable but the arrow before "Some R Code" is missing, whereas I can see it if I view the same page in Chrome.

cc @yonicd

**Comment by hadley** [comment]
Are you sure this isn't a firefox bug? It works fine in safari (and chrome, clearly.)

**Comment by yonicd** [comment]
In my firefox I don't see the triangles, but I can click on the `<summary>` text and it opens up the content.

**Comment by Bisaloo** [comment]
If it helps, I noticed this bug a couple of months ago with a simple `Rmd` document. Not sure if that's Firefox or rmarkdown issue but I don't think it's caused by pkgdown.

````yml
---
title: "Untitled"
author: "Hugo Gruson"
date: "November 12, 2018"
output: html_document
---

<details>
<summary>Details</summary>
    Something small enough to escape casual notice.
</details>
````

**Comment by Bisaloo** [comment]
Looks like it's caused by the

https://github.com/rstudio/rmarkdown/blob/f111cf9601393317bac9cbc0e6dc81336c4fe002/inst/rmd/h/bootstrap/css/bootstrap.css#L27-L29

part.

**Comment by maelle** [comment]
Thanks @Bisaloo, so I should close this issue, right?

**Comment by Bisaloo** [comment]
or maybe @hadley can [transfer it to the rmarkdown repo](https://help.github.com/articles/transferring-an-issue-to-another-repository/)? IDK what works best for you.

**Comment by Bisaloo** [comment]
https://github.com/rstudio/rmarkdown/issues/1260

It might actually be harder than I anticipated to update the bootstrap template. So maybe, this issue should indeed be transfered (or re-open) in the rmarkdown repo to see what the maintainers think of this.

**Comment by maelle** [comment]
Fixed in `rmarkdown`! 🎉 Thanks a lot @Bisaloo!

**Comment by Bisaloo** [comment]
@maelle, I'm sorry but I realized yesterday that the issue in `pkgdown` stems from the same underlying issue in bootstrap but is actually not caused by `rmarkdown` itfself. `pkgdown` uses its own bootstrap version so the fix in `rmarkdown` does not fix the issue you reported here.

I've started #894 to address this issue in `pkgdown`. If it's too complex to switch to bootstrap 4 or if the `pkgdown` maintainers don't want to do it for now, we can always use the same fix as in `rmarkdown` (https://github.com/rstudio/rmarkdown/pull/1485)

Again, sorry for the confusion... :disappointed:

**Comment by maelle** [comment]
Aaah ok thank you!

**Comment by jayhesselberth** [comment]
@Bisaloo Can you confirm whether adding:

```css
summary {
  display: list-item;
}
```

to pkgdown.css fixes this issue and has no side effects?

**Comment by hadley** [comment]
I verified locally. Looks good to me.

**Comment by RWParsons** [comment]
I'm having this same issue when using includeMarkdown() within a shiny app. Arrows do show up correctly in the window from RStudio but when opening the app in a browser (I've tried Chrome, IE, Firefox) the arrows do not show up.  I can create a reproducible example tomorrow if necessary.

**Comment by maelle** [comment]
@RWParsons 

- in general it's not a good idea to comment in a closed issue vs in a new one. :slightly_smiling_face: 
- If the problem is with a Shiny app I'd recommend posting in the Shiny repo or this category of the RStudio community forum: https://community.rstudio.com/c/shiny/8 :memo: 

Good luck! :four_leaf_clover:
